sudo: required
dist: trusty
language: scala
script:
- sbt +compile +tests/run
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_4bc7aeb7f96e_key -iv $encrypted_4bc7aeb7f96e_iv
  -in secrets.tar.enc -out secrets.tar -d
